server:
  port: 8080
  servlet:
    context-path: /users
spring:
  application:
    name: timesheet-project
  datasource:
    url: jdbc:mysql://localhost:3306/timesheet9?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


